### ISSUE TITLE
Calculix error in simulation restart after version 2.10

### ISSUE THREAD

**Issue by KyleDavisSA** [precice/calculix-adapter#11]
Hi everyone

To perform a simulation restart in Calculix, a restart file (file ending in .rin) is read at the beginning of the new simulation. However, after version 2.10 Calculix gives me an error and fails. Has anyone else had this problem with v2.11 and onwards? For now, I use version 2.10 for any simulation that requires a restart. This is not an adapter issue but a problem in Calculix. 

The second problem with the restart is that if a coupled simulation fails, Calculix does not write a restart output file (file ending in .rout). That means a simulation must be re-run with the end time being before where the simulation crashed the first time to generate an output file.

For now, the Calculix adapter is available for version 2.10 as well. The adapters are built in the same way so if someone is able to perform restarts with version 2.15 then that is great, otherwise I know version 2.10 works.

**Comment by BenjaminRodenberg** [comment]
I also did a few experiments with CalculiX and a simple example using [`RESTART`](https://web.mit.edu/calculix_v2.7/CalculiX/ccx_2.7/doc/ccx/node235.html) under Ubuntu 20.04 and found out that

* CalculiX 2.10 built from source works. (www.dhondt.de/ccx_2.10.src.tar.bz2)
* CalculiX 2.11 installed via `sudo apt install calculix-ccx` gives a segmentation fault when reading the `.rin` file.
* CalculiX 2.17 built from source works. (www.dhondt.de/ccx_2.17.src.tar.bz2)

**Comment by uekerman** [comment]
Closing as this is solved upstream by now.
