### ISSUE TITLE
Implement mesh connectivity for e.g. nearest-projection mapping

### ISSUE THREAD

**Issue by uekerman** [precice/calculix-adapter#12]
Define edges and triangles. Any guess how complicated that would be in CalculiX?

**Comment by KyleDavisSA** [comment]
The nearest-projection mapping has been implemented into the CalculiX adapter for v2.15 in the master branch. The instructions on how to perform nearest-projection mapping is in the CalculiX wiki, and a tutorial will be released soon that can perform nearest-projection mapping.

**Comment by uekerman** [comment]
Instructions are in the [readme](https://github.com/precice/calculix-adapter#nearest-projection-mapping), actually.
