### ISSUE TITLE
Linking to OpenMPI fails

### ISSUE THREAD

**Issue by floli** [precice/calculix-adapter#2]
```
gfortran -fopenmp -Wall -O3 -o bin/ccx_preCICE bin/ccx_2.12.o bin/ccx_2.12.a /home/florian/software/calculix/SPOOLES.2.2/spooles.a /home/florian/software/calculix/ARPACK/libarpack_INTEL.a -lpthread -lm -lc -L/home/florian/precice/build/last -lprecice -lboost_regex -lboost_log -lboost_log_setup -lboost_thread -lboost_program_options -lboost_system -lboost_filesystem -lpython2.7 -lstdc++ -lmpi_cxx -lm -lmpi -L/build -lyaml-cpp
/usr/bin/ld: cannot find -lmpi_cxx
collect2: error: ld returned 1 exit status
make: *** [Makefile:87: bin/ccx_preCICE] Error 1
```

Setting ```FC=mpifort``` in the Makefile makes it link successfull.

Using the MPI compiler wraper should be the default, as it is also recommeded by the MPI vendors.

**Comment by arusch** [comment]
Thanks, @floli for pointing out that issue!
I have changed the Makefile according to your suggestion.

Best regards
Alexander

**Comment by floli** [comment]
You should also remove the ```-lmpi -lmpi_cxx``` linking flags, the wrapper will add the necessary flags.

**Comment by uekerman** [comment]
@floli Are you sure that `-lmpi_cxx` can also be removed if `libprecice.a` is linked? Does `mpifort` know that I link a C++ library? I must admit I have not tested this now, but I remember that I had problems with this when I coupled Alya. @arusch Please test this before removing.

**Comment by floli** [comment]
You're right, seems to break the static linking.

**Comment by floli** [comment]
```
% mpifort -show
/usr/bin/gfortran -I/usr/include -pthread -I/usr/lib/openmpi -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -L/usr/lib/openmpi -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
```

I guess so.

**Comment by arusch** [comment]
@floli and @uekerman, I have adapted the Makefile and tested it.
I would appreciate it very much if you could also test it on your machines and let me know whether it worked for you.

**Comment by floli** [comment]
Compiles fine for me.

**Comment by arusch** [comment]
Thanks for your help!
