### ISSUE TITLE
facial distributed load for 2nd order element

### ISSUE THREAD

**Issue by yuxianglin** [precice/calculix-adapter#21]
Hi:

Just curious if I am using 2nd order element in Calculix for heat transfer, there will be three Gauss points in each face of the element, I wonder just provide the facial center value will be enough to integrate the facial flux in the Calculix adapter?

Best,
Yuxiang

**Comment by uekerman** [comment]
Hi! 

We use GitHub issues only for code development, bug reports etc. Could you please re-post your question on the mailing list (or gitter)? See [Contact information](https://www.precice.org/resources/#Contact). Then, I guess you could also reach more people to help you. 

You want to write data to preCICE, right? My naive guess would be that only the facial center values could be enough, but might not give you the most accurate results. But my CalculiX expertise is limited.
