### ISSUE TITLE
write iteration checkpoint include velocity and acceleration

### ISSUE THREAD

**Issue by yuxianglin** [precice/calculix-adapter#22]
Hi:

I wonder if we would need to store the inital velocity and acceleration when write iteration checkpoint and reload them when read_iteration_checkpoint? Since when calculix step before synchronization time, it may update the velocity and acceleration, which should be restored when sub-iteration is needed. Currently the adapter seems only restore the displacement

**Comment by uekerman** [comment]
Thanks for opening this. Is this a duplicate of #9 or how are both related?

**Comment by yuxianglin** [comment]
This might explains why sub-cycling is not working properly

**Comment by uekerman** [comment]
I am closing this issue in favor of #9.
Needless to say, we are very open for contributions to the CalculiX adapter. The CalculiX expertise of the preCICE core developers is limited to some extent.
