### ISSUE TITLE
Issues when running make in calculix-adapter-master

### ISSUE THREAD

**Issue by iamwols** [precice/calculix-adapter#24]
Hello! I am new to GitHub, so I apologise if I am not formatting the question properly.
I am trying to build CalculiX using the make command in calculix-adapter-master, but i ran into the following error:

collect2: error: ld returned 1 exit status
Makefile:101: recipe for target 'bin/ccx_preCICE' failed
make: *** [bin/ccx_preCICE] Error 1

How should I go ahead to fix this?

Thank you!

**Comment by KyleDavisSA** [comment]
Hi iamwols,

would you be able to provide your makefile and a log output when running `make`? Does your CalculiX installation work without installing the adapter?

We typically use the issues section to track bugs and features. For a question on installation, we have a forum on discourse [here](https://precice.discourse.group/) where more people will be able to help. The discourse page is more suited for questions such as installation and general questions around preCICE. You could post a question on discourse with the files mentioned and we can try and help solve the problem :)
