### ISSUE TITLE
Segmentation vialiolation in CalculiX when running OpenFOAM - CCX tutorials

### ISSUE THREAD

**Issue by mlubieniecki** [precice/calculix-adapter#32]
Hello everybody! Yesterday I installed preCICE, OpenFOAM 7, CalculiX 2.15 and their adapters on Ubuntu 18.04. Then I tried to run the tutorial case: FSI/flap-perp/OpenFOAM-CalculiX Unfortunately, I'm constantly reaching this error:

Starting FSI analysis via preCICE using the geometrically non-linear CalculiX solver...
 Using up to 1 cpu(s) for the stress calculation.

 Using up to 1 cpu(s) for the symmetric stiffness/mass contributions.

 Factoring the system of equations using the symmetric spooles solver
 Using 1 cpu for spooles.

 Using up to 1 cpu(s) for the stress calculation.

About to enter preCICE setup in Calculix with names Calculix and config.yml 
Setting up preCICE participant Calculix, using config file: config.yml
./runSolid: line 19:  3892 Segmentation fault      (core dumped) ccx_preCICE -i Solid/flap -precice-participant Calculix

Then I tried to run any other tutorial case and they all end the same way. The OpenFOAM adapter seems to be working correctly and there were no issues with making CCX_preCICE or its dependencies. It also seems to run fine given a standalone .inp file. Any ideas how to find the cause of that? Thank you very much for help. It's my first post in GitHub issues so if I posted this in the wrong place feel free to move it or direct me somewhere else.
Kind regards,
Marek Lubieniecki

**Comment by uekerman** [comment]
Solved on gitter.
