### ISSUE TITLE
No support for missing write-data / read-data

### ISSUE THREAD

**Issue by MakisH** [precice/calculix-adapter#35]
Removing the `write-data` node (or defining `write-data: []`) seems to trigger a bad conversion:
```
About to enter preCICE setup in Calculix with names Calculix and config.yml 
Setting up preCICE participant Calculix, using config file: config.yml
terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  bad conversion
```

As a workaround, `write-data: ""` seems to pass, but then it fails with `ERROR:  There is no Mesh with ID:-1`

Here is the respective code:
https://github.com/precice/calculix-adapter/blob/73a9a062e3cd3a0c8d01d480950fc7f3172037a4/adapter/ConfigReader.cpp#L65-L81

It looks like we always ask for at least one writer.

This essentially means that currently the CalculiX adapter does not support one-way coupling due to some configuration reading issue that could easily be solved.

**Comment by KyleDavisSA** [comment]
I have push a change to branch v2.16. However, this requires the entire `write-data` or `read-data` be removed from the config. Just deleting the data name so that `write-data = [ ]` does not work yet.

**Comment by MakisH** [comment]
Nice! If you think it is ready, could you also update develop & master?

**Comment by bitronTeofil** [comment]
In the last days I was trying a one way coupling that is very similar to the sloshing 2D tank of the OF tutorial distribution.

![image](https://user-images.githubusercontent.com/54403102/77806807-15175280-7086-11ea-8b8e-72986e7f46ae.png)

Unfortunately I found the same CalculiX error:

About to enter preCICE setup in Calculix with names Calculix and config.yml 
Setting up preCICE participant Calculix, using config file: config.yml
terminate called after throwing an instance of 'YAML::TypedBadConversion<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >'
  what():  bad conversion
Aborted (core dumped)

Please, could you explain me better the Kyle solution?

**Comment by KyleDavisSA** [comment]
Could you add your config.yml file for Calculix? The visual result of your precice-config file looks fine. The changes in the v2.16 branch, which we should be merging to develop soon.

Regarding your problem. I believe from a coupling perspective it should work if the mapping is done at the beginning before any rotation takes place. From a modelling perspectice, it might results in some erroneous results as there isn't any rotation that CalculiX is aware of. Although, if the rotation is applied to all Calculix elements, perhaps that might not result in very big differences, but that might not be the physical problem where something needs to cause a rotation, such as a shaft. In that case, those stresses are not accounted for.

**Comment by bitronTeofil** [comment]
hello Kyle, I recompiled the update adapter for CalculiX v. 2.16 and now the one way coupling runs well.
Unfortunately I realize that this sim in 2d doesn't have to much sense, so I realize a 3d version.

![image](https://user-images.githubusercontent.com/54403102/78351290-d7935780-75a6-11ea-9741-c4d9c385e006.png)

When I finish in preparing the model I could present some results. This is just an example, and I would like to consider the inertia forces of the fluid due to the sloshing inside on the tank walls.
