### ISSUE TITLE
Error solving the tutorial: flap_perp/OpenFOAM-CalculiX

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [precice/calculix-adapter#43]
I have installed both OpenFOAM and Calculix adapters without errors. Now when I run the Flap case I get the following error in the fluid terminal:
```
---[precice] ERROR:  The interpolation matrix of the RBF mapping from mesh Fluid-Mesh-Faces to mesh Solid is not invertable. This means that the mapping problem is not well-posed. Please check if your coupling meshes are correct. Maybe you need to fix axis-aligned mapping setups by marking perpendicular axes as dead?
```
OpenFOAM version is 7.0. I first run `runFluid` script and in another terminal I run `runSolid` script.

**Comment by IshaanDesai** [comment]
This is resolved in https://github.com/precice/tutorials/issues/112
