### ISSUE TITLE
Requiring "Velocity" instead of "Velocities" breaks other adapters and schemes

### ISSUE THREAD

**Issue by j8asic** [precice/calculix-adapter#64]
At the line: https://github.com/precice/calculix-adapter/blob/d4db584237f5efdeb1f8da3d294d9766716ef711/adapter/PreciceInterface.c#L780
it says the requirement is that the tag must start with `"Velocity"`. Formerly the requirements was `"Velocities"`. Since we're talking about nodes, some prefer plural. Can you make the requirement to be: `if ( startsWith( config->writeDataNames[i], "Velocit" ) )` so both cases are covered?

**Comment by IshaanDesai** [comment]
Thanks for this! It is fixed in https://github.com/precice/calculix-adapter/commit/caf3fe8004c6534ff2d5eeefcecaff2770a497f5
