### ISSUE TITLE
small bugs with mapping2D3D in case of mesh between 0 and H

### ISSUE THREAD

**Issue by CyrilleBonamy** [precice/calculix-adapter#65]
Hello everyone,
Thanks a lot for your incredible work.

I found small bugs with mapping2D3D. **In the following i consider that the 2D3D direction is z.**

First, the mapping2D3D requires one side of the mesh to be z = 0. I did not find an explanation on this point in the documentation. Maybe it can be specified somewhere.
Secondly, the mapping2D3D requires the mesh to be between z = -H and z = 0. If the mesh is between z = 0 and z = H, there is a problem with the mapping. The simulation runs but the mapping is false. A workaround is to modify the preciceInterface.c : 

```
diff --git a/adapter/PreciceInterface.c b/adapter/PreciceInterface.c
index b5d718b..7446e72 100644
--- a/adapter/PreciceInterface.c
+++ b/adapter/PreciceInterface.c
@@ -568,7 +568,7 @@ void PreciceInterface_ConfigureNodesMesh( PreciceInterface * interface, Simulati
             isDoubleEqual(interface->nodeCoordinates[ii*dimCCX + 1], interface->nodeCoordinates[i*dimCCX + 1]) &&
             !isDoubleEqual(interface->nodeCoordinates[ii*dimCCX + 2], interface->nodeCoordinates[i*dimCCX + 2]))
         {
-          if ( !isDoubleEqual(interface->nodeCoordinates[i*dimCCX + 2], 0.0) )
+          if ( !isDoubleEqual(interface->nodeCoordinates[ii*dimCCX + 2], 0.0) )
           {
             interface->mapping2D3D[i] = count;
             interface->mapping2D3D[ii] = count;
```
I think we can easily found a better solution to support both cases. If you want i can propose a patch to do it.

And again,  I did not found an explanation on this point in the documentation. Maybe it can be specified somewhere.

Thank you again for your very nice work, 

Cyrille

**Comment by DavidSCN** [comment]
Question here goes probably to @IshaanDesai, but let me add a small comment: if you couple OpenFOAM, the out-of-plane direction has to be the z-axis as well: https://github.com/precice/openfoam-adapter/blob/aab511c0756f9dc50b542d2c9166502b5ee56a9d/Interface.C#L99-L144

This is related to how we read and write data from the OpenFOAM fields. With a vast usage of `if` and some configuration options one could make this configurable of course, but I don't see any benefit (again, talking about the OpenFOAM side).

**Comment by CyrilleBonamy** [comment]
> Question here goes probably to @IshaanDesai, but let me add a small comment: if you couple OpenFOAM, the out-of-plane direction has to be the z-axis as well: https://github.com/precice/openfoam-adapter/blob/aab511c0756f9dc50b542d2c9166502b5ee56a9d/Interface.C#L99-L144
> 
> This is related to how we read and write data from the OpenFOAM fields. With a vast usage of `if` and some configuration options one could make this configurable of course, but I don't see any benefit (again, talking about the OpenFOAM side).

I agree with that. 👍 
My main remark concerns the fact that with a mesh that goes from Z = 0 to Z = L, the mapping is buggy

**Comment by IshaanDesai** [comment]
>  My main remark concerns the fact that with a mesh that goes from Z = 0 to Z = L, the mapping is buggy

I understand this bug and should be straightforward to fix. I will push a fix to develop today and then you can try again. Thanks for catching this @CyrilleBonamy !

**Comment by CyrilleBonamy** [comment]
No problem. With my fix it works :-)

**Comment by DavidSCN** [comment]
> I agree with that. +1
My main remark concerns the fact that with a mesh that goes from Z = 0 to Z = L, the mapping is buggy

Ah sorry, I guess it was too early in the morning when reading your description.

**Comment by IshaanDesai** [comment]
> No problem. With my fix it works :-)

@CyrilleBonamy if you have a patch already then can you please open a pull request? I can then quickly review it and merge to develop.
