### ISSUE TITLE
Makefile: -lmpi_cxx should not be needed

### ISSUE THREAD

**Issue by MakisH** [precice/calculix-adapter#7]
https://github.com/precice/calculix-adapter/blob/7db6969e0eb9bfeeb6a8c97d3a93a1be9d369692/Makefile#L33

Moreover, this line may create problems when `libmpi_cxx` is not installed (rare cases).

I open this issue as a hint for people that may run into this problem. Please also try building without this line and let us know if you have any problems.

I suggest that we remove this line and revert the change if anyone complains.

**Comment by IshaanDesai** [comment]
This flag is not longer present in the [Makefile](https://github.com/precice/calculix-adapter/blob/eadedeef0a1a4e2e2c7a5d164faccd7b40012347/Makefile)
