### ISSUE TITLE
Null essential (Dirichlet) boundary condition imposed on node 1

### ISSUE THREAD

**Issue by AndresPedemonteFIUBA** [precice/calculix-adapter#86]
Hey,

I have experienced a problem with the adapter for CalculiX 2.16 where node number 1 of the CalculiX mesh has a null Dirichlet BC imposed on it for every increment/time step of a simulation. This happens even when there are no BCs specified for that node. In the case of an FSI simulation this means node 1 stays fixed; it's displacement is always zero. 

Others have reported this issue as well:

- [CalculiX single node stagnation problem](https://precice.discourse.group/t/calculix-single-node-stagnation-problem/518) (Specially, check out post number 3).
- [FSI SU2/CalculiX (flap_perp): CalculiX node ID#1 is fixed](https://github.com/precice/tutorials/issues/90)
- [How can I create a Solid mesh for working with the nearest neighbor mapping?](https://precice.discourse.group/t/how-can-i-create-a-solid-mesh-for-working-with-the-nearest-neighbor-mapping/243) (See post number 4 by Kyle Davis)
- [Temperature anomaly/ Calculix OpenFoam CHT Coupling](https://precice.discourse.group/t/temperature-anomaly-calculix-openfoam-cht-coupling/915)

The last one seems to indicate this problem also happens for CHT simulations. In that case, for node number 1 T = 0 K.

An easy way to reproduce it is by modifying the `perpendicular-flap` tutorial. Just exchange nodes `1` and `738` in the `*NODE` and `*ELEMENT` keywords. Also, change node `1` to `738` in node set `Nfix1` (`fix1_beam.nam` file). You should get something like this:
![Screenshot from 2022-02-15 20-36-56](https://user-images.githubusercontent.com/67233283/154168477-eae766a0-142d-4ed2-ae6f-621770827cf4.png)
That fixed vertex is node `1`. This is for `t=0.3 s`; CalculiX (adapter for 2.16) coupled with OpenFOAM (v7 .org, version 1.0 of the adapter), preCICE 2.3.0, Ubuntu 20.04 LTS.

I have not tested the adapter for CalculiX 2.19 and cannot say wether this shows up with it.

Best regards,
Andrés

**Comment by boris-martin** [comment]
Hi Andres. Thanks for finding out and documenting this. I successfully managed to reproduce it (the perpendicular flap) with both 2.16 and 2.19 versions of the adapter. I'll investigate this :)

You mentioned `t=0.3s` for the screenshot. Does the simulation crash if you keep the default configuration (simulate until `5s`) ? I have this and assume it's because the flap becomes so distorted that implicit coupling breaks, but a confirmation would be nice. But if you don't have time, I have enough material to launch my investigation anyway!

**Comment by AndresPedemonteFIUBA** [comment]
Hi Boris,

No, the simulation does not crash when exchanging nodes `1` and `738` as I suggested and keeping the default configuration. It runs the full 5 seconds, though of course that vertex stays in place. 

Andrés

**Comment by MatthiasFreimuth** [comment]
The problem with the 0 displacement on node 1 seems to be no problem in the modal dynamic analysis case, but only in the dynamic analysis case. At least for my testcase there are problems with the latter but not with the former method.

**Comment by MatthiasFreimuth** [comment]
I had a look into the nonlingeo_precice.c and the dyna_precice.c. 
A different behaviour here seems to occur during the memcpy command directly before the WriteCouplingData routine is called. Here the displacement(vold) of node 1(index 0) is set to zero in the nonlingeo case, which I guess is not the behaviour we want.
One difference is, that in dyna_precice.c we call WriteCouplingData after CalculiX's 'results' and 'frd' routine at the very end of the increment loop. In nonlingeo_precice.c we call WriteCouplingData before the last CalculiX routines (e.g. 'results', 'frd', ...). 
Maybe those observations help, to look further into this and solve the issue.

**Comment by boris-martin** [comment]
> I had a look into the nonlingeo_precice.c and the dyna_precice.c. A different behaviour here seems to occur during the memcpy command directly before the WriteCouplingData routine is called. Here the displacement(vold) of node 1(index 0) is set to zero in the nonlingeo case, which I guess is not the behaviour we want. One difference is, that in dyna_precice.c we call WriteCouplingData after CalculiX's 'results' and 'frd' routine at the very end of the increment loop. In nonlingeo_precice.c we call WriteCouplingData before the last CalculiX routines (e.g. 'results', 'frd', ...). Maybe those observations help, to look further into this and solve the issue.

I don't see how the memcpy should affect the result, but completely removing it seems to fix the issue. I'm currently investigating whether removing it has unanticipated side effects; if there are none I guess we'll simply remove it for good!
