### ISSUE TITLE
Difference between faces-mesh and mesh ?

### ISSUE THREAD

**Issue by boris-martin** [precice/calculix-adapter#87]
I'm slightly confused by the different kinds of interfaces available.
From what I understand, we propose three different things:
- Nodal mesh without connectivity, for e.g. FSI with nearest neighbor or RBF mapping. Configuration is `nodes-mesh`
- Nodal mesh with connectivity, for same context but when nearest projection is used. Configuration is `nodes-mesh-with-connectivity`
- Face centers mesh for CHT. Configuration is either `mesh` or `faces-mesh`.

In the config reader code `mesh` and `faces-mesh` seem to have a different treatment. I think it's just a matter of style, but shouldn't it be a "if(mesh) else if (faces-mesh) else" instead of this "if-else-if" ?
I'm working on some refactoring but I'd rather have confirmation they're equivalent to be sure.

https://github.com/precice/calculix-adapter/blob/4496e8f160ec121481653baf44ec032813409ac6/adapter/ConfigReader.cpp#L36-L55

Also, documentation on [the website](https://precice.org/adapter-calculix-config.html) seems quite lacking. I'll work on it once I'm sure I don't have a major misunderstanding :)

**Comment by MatthiasFreimuth** [comment]
I also use the faces-mesh for a FSI scenario in case of exchange-data pressure. So at least the statement that faces-mesh is for CHT only needs to be questioned in that case. (I added the pressure exchange data and will make a pull request with those changes soon)

**Comment by boris-martin** [comment]
Glad to learn this! 
When I wrote faces were CHT-only, I meant it as "in the current state of the adapter" but pressure on faces definitely makes sense. Looking forward to the PR!
