### ISSUE TITLE
Add more supported elements to CHT simulations

### ISSUE THREAD

**Issue by boris-martin** [precice/calculix-adapter#89]
As of now, CHT simulations (more generally, simulations needing element face centers instead of nodes) only work with tetrahedrons.  (Probably *only first order tetrahedrons* but I haven't tested)
Using different elements (Say brick hexaedrons elements) crashes with no explicit messages but a segfault.

This part is problematic:

https://github.com/precice/calculix-adapter/blob/4496e8f160ec121481653baf44ec032813409ac6/adapter/PreciceInterface.c#L466-L472

- Function `PreciceInterface_ConfigureFaceCentersMesh` assumes tetrahedrons but should be adaptable +/- easily, as it calls a subroutine `getTetraFaceCenters` which is tetrahedron-specific
- PreciceInterface_ConfigureTetraFaces seems to be only required for connectivity but is always called (why?). This code is of course quite specific to the geometry.

I'd like to try to improve that in the near future, but I'm not 100% sure of the best approach:

- How do we detect element type ? Should we dive deeper into CalculiX code to detect each element and treat it accordingly ?
- Should we instead have only one type of elements (tetra or hexa) allowed (in the sense of "no mix") ? If so, is it detectable automatically, or should we add this as an option in the `config.yml` file?
- What about higher order elements ? wedge elements ? Supporting all elements could be complex.
- For connectivity, I read that supporte for quad elements on the interface is experimental. Is it safe to use ?

**Comment by MatthiasFreimuth** [comment]
Hi Boris,
I actually already implemented some way of support for hexahedral elements, in my case I needed it for a DLOAD card, so to apply pressure values in CalculiX. I'm about to make a pull request with my changes soon and then we can use this as a starting point for further discussions about this topic.

**Comment by boris-martin** [comment]
Looking forward to it, thanks! It can probably wait for the actual PR, but how do you handle mixed meshes ? Do you detect for each element what kind it is? Do you only detect the element type of a single-type mesh? Or is that a configuration thing ?

**Comment by MatthiasFreimuth** [comment]
Actually I only use single-type meshes, so no mixed meshes. One can detect the element type directly from the CalculiX variable lakon. You can find it in the list of variables in the CalculiX documentation.
